CREATE DATABASE seriesmanager;

CREATE TABLE users (
    id VARCHAR(50) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE series (
    id NUMERIC PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    poster VARCHAR(150),
    fk_user VARCHAR(50) NOT NULL REFERENCES users(id)
);