CREATE DATABASE seriesmanager;

CREATE TABLE users (
    id VARCHAR(50) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE series (
    id NUMERIC PRIMARY KEY,
    fk_user VARCHAR NOT NULL REFERENCES users(id)
);